# Operating System Applications
choco install -y chocolateygui
choco install -y 7zip.install
choco install -y conemu
choco install -y qdir
choco install -y winscp
choco install -y windirstat
choco install -y googlechrome
choco install -y firefox
choco install -y notepadplusplus.install
choco install -y microsoft-teams
choco install -y slack
choco install -y itunes
choco install -y inkscape
choco install -y 7-taskbar-tweaker

# Developer Tools
choco install -y nginx
choco install -y curl
choco install -y adoptopenjdk11
choco install -y maven
choco install -y nodejs-lts
choco install -y cloudfoundry-cli
choco install -y git.install
choco install -y gitextensions
choco install -y beyondcompare
choco install -y postman
choco install -y putty.install
choco install -y jetbrainstoolbox
choco install -y intellijidea-ultimate
choco install -y webstorm
choco install -y datagrip
choco install -y autohotkey